//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbobusMobile.AndroidRoot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbobusMobile.AndroidRoot.Resources.ApplicationTexts", typeof(ApplicationTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed.
        /// </summary>
        internal static string LoginPage_AuthorizationFailed {
            get {
                return ResourceManager.GetString("LoginPage_AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginPage_EmailLabelText {
            get {
                return ResourceManager.GetString("LoginPage_EmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string LoginPage_EmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPage_LoginButtonText {
            get {
                return ResourceManager.GetString("LoginPage_LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPage_PasswordLabelText {
            get {
                return ResourceManager.GetString("LoginPage_PasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string LoginPage_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LoginPage_RegisterButtonText {
            get {
                return ResourceManager.GetString("LoginPage_RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Authorize.
        /// </summary>
        internal static string LoginPage_TitleText {
            get {
                return ResourceManager.GetString("LoginPage_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited cities:.
        /// </summary>
        internal static string ProfilePage_Cities {
            get {
                return ResourceManager.GetString("ProfilePage_Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed Distance:.
        /// </summary>
        internal static string ProfilePage_Distance {
            get {
                return ResourceManager.GetString("ProfilePage_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string ProfilePage_Email {
            get {
                return ResourceManager.GetString("ProfilePage_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends:.
        /// </summary>
        internal static string ProfilePage_Friends {
            get {
                return ResourceManager.GetString("ProfilePage_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string ProfilePage_Logout {
            get {
                return ResourceManager.GetString("ProfilePage_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string ProfilePage_LogoutEnsure {
            get {
                return ResourceManager.GetString("ProfilePage_LogoutEnsure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Routes:.
        /// </summary>
        internal static string ProfilePage_Routes {
            get {
                return ResourceManager.GetString("ProfilePage_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ProfilePage_Settings {
            get {
                return ResourceManager.GetString("ProfilePage_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile.
        /// </summary>
        internal static string ProfilePage_TitleText {
            get {
                return ResourceManager.GetString("ProfilePage_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string ProfilePage_Username {
            get {
                return ResourceManager.GetString("ProfilePage_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Routes.
        /// </summary>
        internal static string RoutesPage_AdditionalRoutes {
            get {
                return ResourceManager.GetString("RoutesPage_AdditionalRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Routes.
        /// </summary>
        internal static string RoutesPage_AvailableRoutes {
            get {
                return ResourceManager.GetString("RoutesPage_AvailableRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your City:.
        /// </summary>
        internal static string RoutesPage_ChooseCityTitle {
            get {
                return ResourceManager.GetString("RoutesPage_ChooseCityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string RoutesPage_CityNotFound {
            get {
                return ResourceManager.GetString("RoutesPage_CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded Routes.
        /// </summary>
        internal static string RoutesPage_DownloadedRoutes {
            get {
                return ResourceManager.GetString("RoutesPage_DownloadedRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string RoutesPage_TitleText {
            get {
                return ResourceManager.GetString("RoutesPage_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Routes.
        /// </summary>
        internal static string RoutesPage_YourRoutes {
            get {
                return ResourceManager.GetString("RoutesPage_YourRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abobus App.
        /// </summary>
        internal static string StartPage_AppName {
            get {
                return ResourceManager.GetString("StartPage_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string StartPage_WelcomeMessage {
            get {
                return ResourceManager.GetString("StartPage_WelcomeMessage", resourceCulture);
            }
        }
    }
}
